version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres

  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/postgres
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend
