services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_database}

  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_database}
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend